description="Creates a new council collector from a HAR file."
prompt = """
You are an AI coding agent tasked with implementing a new council collector for the BinDays API.

**Your primary goal is to use the `requests.har` file and its associated data to implement the collector.**

The necessary files are located in the `tmp_collector_data` directory:
-   `requests.har`: The HAR file containing all network traffic.
-   `council_info.json`: Contains the council's name, GovUkId, and website URL.
-   A set of attachment files (e.g., `...json`, `...html`) containing the response bodies.

**Workflow:**

1.  **Analyze the HAR File:**
    -   Read and parse the `tmp_collector_data/requests.har` file.
    -   Identify the specific network requests in the HAR `entries` that are responsible for:
        a.  Fetching the list of addresses.
        b.  Fetching the bin collection data.
    -   For each of these relevant requests, find the filename of the attached response body in the `content._file` field.

2.  **Read Data Files:**
    -   Read the `tmp_collector_data/council_info.json` file.
    -   Read the content of the response body attachment files you identified in the previous step. **Ignore irrelevant assets like CSS, images, or fonts.**

3.  **Implement and Test:**
    -   Using the data from the HAR file and the response bodies, implement the new council collector class in `BinDays.Api.Collectors/Collectors/Councils/`.
    -   Pay close attention to request URLs, methods, headers, and payloads from the HAR entries.
    -   Implement the corresponding integration test in `BinDays.Api.IntegrationTests/Collectors/Councils/`.
    -   Run the test and debug until it passes.
"""
