description="Fetches and saves the required data for a new council collector."
prompt = """
You are an AI coding agent tasked with the first step of adding support to the BinDays API for a new council: data gathering. You must follow all principles and instructions in the `GEMINI.md` file.

The postcode for this task is: **{{args}}**

Your detailed workflow is as follows:

1.  **Initial Government Website Investigation:**
    - Navigate to the UK government bin collection page (`https://www.gov.uk/rubbish-collection-day`) and enter the postcode `{{args}}`.
    - Record the full council name, the `GovUkId` from the URL, and the link to the council's official website. Store this information in a file named `.collector_data/council_info.json`.

2.  **Detailed Council Website Investigation:**
    - Navigate to the council website link you just recorded.
    - Find the bin or waste collection page.
    - Script the process of entering the postcode and submitting the form.
    - The website should return a list of addresses. Script the selection of the *first* address in the list.
    - After selecting the address, the page should display the upcoming bin collections.

3.  **Network Request Analysis and Saving:**
    - **This is the most critical step.** During the entire process above, you must meticulously record the network requests and their responses and save them as HAR files.
    - Save the captured network interaction for the initial page load as a HAR file named `.collector_data/initial_page_load.har`.
    - Save the captured network interaction for the address lookup as a HAR file named `.collector_data/address_lookup.har`.
    - Save the captured network interaction for the bin day lookup as a HAR file named `.collector_data/bin_day_lookup.har`.
"""
