description="Fetches and saves the required data for a new council collector using HAR recording."
prompt = """
You are an AI coding agent tasked with gathering data to support a new council in the BinDays API.

**Your primary goal is to generate a HAR (HTTP Archive) file containing all network traffic for the user journey.**

**Workflow:**

1.  **Initial Setup:**
    -   Create a `tmp_collector_data` directory if it doesn't exist.
    -   Launch a browser with HAR recording enabled.

2.  **Website Navigation:**
    -   Navigate to the UK government bin collection page (`https://www.gov.uk/rubbish-collection-day`) and enter the postcode `{{args}}`.
    -   Follow the link to the specific council's website.
    -   On the council's website, find the bin/waste collection page.
    -   Script the process of entering the postcode and selecting the first address from the results.
    -   Navigate to the page that displays the bin collection schedule.
    -   Also, record the full council name, the `GovUkId` from the URL, and the link to the council's official website. Store this information in a file named `tmp_collector_data/council_info.json`.

3.  **Finalize HAR Recording:**
    -   **Crucially, you must close the browser session.** The `requests.har` file and its attachments are only written to disk when the browser context is closed.

Your task is complete once the `tmp_collector_data` directory contains the `requests.har` file, the `council_info.json` file, and all the associated response body files.
"""
