namespace BinDays.Api.SourceGenerators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

/// <summary>
/// Generates an MCP tool class from any controller marked with <c>[GenerateMcpTools]</c>.
/// Only <c>[HttpGet]</c>, <c>[HttpPost]</c>, and <c>[HttpDelete]</c> actions are included.
/// </summary>
[Generator]
public sealed class McpToolsGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static ctx => ctx.AddSource(
			"GenerateMcpToolsAttribute.g.cs",
			"// <auto-generated/>\n[System.AttributeUsage(System.AttributeTargets.Class)]\ninternal sealed class GenerateMcpToolsAttribute : System.Attribute { }\n"
		));

		var controllers = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"GenerateMcpToolsAttribute",
				predicate: static (node, _) => node is ClassDeclarationSyntax,
				transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
			.Collect();

		context.RegisterSourceOutput(controllers, static (ctx, symbols) =>
		{
			foreach (var symbol in symbols)
			{
				ctx.AddSource($"{symbol.Name}McpTools.g.cs", GenerateSource(symbol));
			}
		});
	}

	/// <summary>
	/// Generates the full MCP tool class source for the given controller symbol.
	/// </summary>
	private static string GenerateSource(INamedTypeSymbol controller)
	{
		var controllerNs = controller.ContainingNamespace.ToDisplayString();
		var toolsNs = controllerNs.Replace(".Controllers", ".Mcp");
		var qualifiedName = controller.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		var controllerPrefix = controller.Name.Replace("Controller", string.Empty);

		var ctor = controller.Constructors.FirstOrDefault(c => !c.IsImplicitlyDeclared);
		var ctorParams = ctor?.Parameters ?? ImmutableArray<IParameterSymbol>.Empty;

		var actions = controller.GetMembers()
			.OfType<IMethodSymbol>()
			.Where(m => m.MethodKind == MethodKind.Ordinary
					 && m.DeclaredAccessibility == Accessibility.Public
					 && m.GetAttributes().Any(a => a.AttributeClass?.Name is "HttpGetAttribute" or "HttpPostAttribute" or "HttpDeleteAttribute"))
			.ToArray();

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine($"namespace {toolsNs};");
		sb.AppendLine();
		sb.AppendLine("using System.ComponentModel;");
		sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
		sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
		sb.AppendLine("using ModelContextProtocol.Server;");
		sb.AppendLine();
		sb.AppendLine("[McpServerToolType]");
		sb.AppendLine($"internal sealed class {controller.Name}McpTools(global::System.IServiceProvider services)");
		sb.AppendLine("{");

		EmitCreateController(sb, qualifiedName, ctorParams);
		EmitConvert(sb);

		foreach (var action in actions)
		{
			EmitToolMethod(sb, action, controllerPrefix);
		}

		sb.AppendLine("}");
		return sb.ToString();
	}

	/// <summary>
	/// Emits the CreateController helper method that resolves controller dependencies from the DI container.
	/// </summary>
	private static void EmitCreateController(StringBuilder sb, string qualifiedName, ImmutableArray<IParameterSymbol> ctorParams)
	{
		sb.AppendLine($"    private {qualifiedName}? CreateController()");
		sb.AppendLine("    {");

		foreach (var p in ctorParams)
		{
			var typeName = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			sb.AppendLine($"        var {p.Name} = services.GetService<{typeName}>();");
		}

		if (ctorParams.Length > 0)
		{
			var check = string.Join(" || ", ctorParams.Select(p => $"{p.Name} is null"));
			sb.AppendLine($"        if ({check})");
			sb.AppendLine("        {");
			sb.AppendLine("            return null;");
			sb.AppendLine("        }");
		}

		sb.AppendLine($"        return new {qualifiedName}({string.Join(", ", ctorParams.Select(p => p.Name))});");
		sb.AppendLine("    }");
		sb.AppendLine();
	}

	/// <summary>
	/// Emits the Convert helper method that maps an IActionResult to a string for MCP tool responses.
	/// </summary>
	private static void EmitConvert(StringBuilder sb)
	{
		sb.AppendLine("    private static string Convert(IActionResult result) => result switch");
		sb.AppendLine("    {");
		sb.AppendLine("        ContentResult { Content: var content } => content ?? string.Empty,");
		sb.AppendLine("        OkObjectResult { Value: var value } => global::Newtonsoft.Json.JsonConvert.SerializeObject(value),");
		sb.AppendLine("        NotFoundResult => \"Not found.\",");
		sb.AppendLine("        NoContentResult => \"Done.\",");
		sb.AppendLine("        _ => string.Empty,");
		sb.AppendLine("    };");
	}

	/// <summary>
	/// Emits a single MCP tool method that delegates to the corresponding controller action.
	/// </summary>
	private static void EmitToolMethod(StringBuilder sb, IMethodSymbol action, string controllerPrefix)
	{
		sb.AppendLine();
		var xml = action.GetDocumentationCommentXml() ?? string.Empty;
		var description = GetToolDescription(action, xml);
		var paramDocs = GetXmlParams(xml);
		var toolName = $"{controllerPrefix}{action.Name}";

		sb.AppendLine($"    [McpServerTool, Description(\"{Escape(description)}\")]");

		var paramList = string.Join(", ", action.Parameters.Select(p =>
		{
			paramDocs.TryGetValue(p.Name, out var desc);
			var descAttr = desc != null ? $"[Description(\"{Escape(desc)}\")] " : "";
			var typeName = GetParamTypeName(p);
			var defaultVal = p.HasExplicitDefaultValue ? $" = {FormatDefault(p.ExplicitDefaultValue)}" : "";
			return $"{descAttr}{typeName} {p.Name}{defaultVal}";
		}));

		sb.AppendLine($"    public string {toolName}({paramList})");
		sb.AppendLine("    {");
		sb.AppendLine("        if (CreateController() is not { } controller)");
		sb.AppendLine("        {");
		sb.AppendLine("            return \"Failed to resolve controller dependencies.\";");
		sb.AppendLine("        }");
		sb.AppendLine($"        return Convert(controller.{action.Name}({string.Join(", ", action.Parameters.Select(p => p.Name))}));");
		sb.AppendLine("    }");
	}

	/// <summary>
	/// Returns the tool description from attributes or XML documentation for the given action.
	/// </summary>
	private static string GetToolDescription(IMethodSymbol method, string xml)
	{
		foreach (var attrName in new[] { "EndpointDescriptionAttribute", "EndpointSummaryAttribute" })
		{
			var attr = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == attrName);
			if (attr?.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string s && s.Length > 0)
			{
				return s;
			}
		}

		return GetXmlText(xml, "summary");
	}

	/// <summary>
	/// Returns the C# type name for a parameter symbol, appending '?' for nullable reference types.
	/// </summary>
	private static string GetParamTypeName(IParameterSymbol p)
	{
		var name = p.Type.ToDisplayString();
		if (p.NullableAnnotation == NullableAnnotation.Annotated && p.Type.IsReferenceType && !name.EndsWith("?"))
		{
			name += "?";
		}

		return name;
	}

	/// <summary>
	/// Extracts and normalizes the text content of a named XML element from documentation XML.
	/// </summary>
	private static string GetXmlText(string xml, string element)
	{
		if (string.IsNullOrEmpty(xml))
		{
			return string.Empty;
		}

		var text = XDocument.Parse(xml).Root?.Element(element)?.Value ?? string.Empty;
		return Regex.Replace(text.Trim(), @"\s+", " ");
	}

	/// <summary>
	/// Extracts parameter descriptions from XML documentation comments into a name-to-description dictionary.
	/// </summary>
	private static Dictionary<string, string> GetXmlParams(string xml)
	{
		var result = new Dictionary<string, string>();

		if (string.IsNullOrEmpty(xml))
		{
			return result;
		}

		foreach (var el in XDocument.Parse(xml).Root?.Elements("param") ?? Enumerable.Empty<XElement>())
		{
			var name = el.Attribute("name")?.Value;
			if (name != null)
			{
				result[name] = Regex.Replace(el.Value.Trim(), @"\s+", " ");
			}
		}

		return result;
	}

	/// <summary>
	/// Escapes backslashes, quotes, and newlines in a string for embedding in a C# string literal.
	/// </summary>
	private static string Escape(string s)
		=> s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "").Replace("\n", " ");

	/// <summary>
	/// Formats a default parameter value as a C# literal expression.
	/// </summary>
	private static string FormatDefault(object? val) => val switch
	{
		null => "null",
		string s => $"\"{s}\"",
		bool b => b ? "true" : "false",
		_ => val?.ToString() ?? "null",
	};
}
