name: Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - BinDays.Api/**
      - BinDays.Api.Collectors/**

jobs:
  build-and-push-bindays-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Build Image
        run: make build-bindays-api

      - name: Tag and Push Image
        run: |
          VERSION=$(make version)
          SOURCE_IMAGE="bindays-api:$VERSION"
          SOURCE_IMAGE_LATEST="bindays-api:latest"

          TARGET_IMAGE="ghcr.io/${{ secrets.GHCR_USERNAME }}/$SOURCE_IMAGE"
          TARGET_IMAGE_LATEST="ghcr.io/${{ secrets.GHCR_USERNAME }}/$SOURCE_IMAGE_LATEST"

          docker tag $SOURCE_IMAGE $TARGET_IMAGE
          docker tag $SOURCE_IMAGE_LATEST $TARGET_IMAGE_LATEST
          docker push $TARGET_IMAGE
          docker push $TARGET_IMAGE_LATEST
