name: Deploy to DigitalOcean
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed

jobs:
  deploy_to_digitalocean:
    runs-on: ubuntu-latest

    env:
      TF_VAR_do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      TF_VAR_ghcr_username: ${{ secrets.GHCR_USERNAME }}
      TF_VAR_ghcr_access_token: ${{ secrets.GHCR_ACCESS_TOKEN }}
      TF_VAR_docker_image: dgatdo-application:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Encrypted Artifact & Decrypt Artifact
        uses: badgerhobbs/terraform-state@v1
        with:
          encryption_key: ${{ secrets.encryption_key }}
          operation: download
          location: artifact
          directory: ./Terraform
          github_token: ${{ secrets.gh_access_token }}
        continue-on-error: true

      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ssh_key }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform -chdir="./Terraform" init

      - name: Run Terraform Plan
        run: |
          terraform -chdir="./Terraform" plan

      - name: Deploy to DigitalOcean
        run: |
          terraform -chdir="./Terraform" apply -auto-approve

      - name: Encrypt Artifact & Upload Encrypted Artifact
        uses: badgerhobbs/terraform-state@v1
        with:
          encryption_key: ${{ secrets.encryption_key }}
          operation: upload
          location: artifact
          directory: ./Terraform
          github_token: ${{ secrets.gh_access_token }}
